/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kgaft_ResonanceEngine_Native_VulkanContext_VulkanContext */

#ifndef _Included_com_kgaft_ResonanceEngine_Native_VulkanContext_VulkanContext
#define _Included_com_kgaft_ResonanceEngine_Native_VulkanContext_VulkanContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kgaft_ResonanceEngine_Native_VulkanContext_VulkanContext
 * Method:    initializeInstance
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_kgaft_ResonanceEngine_Native_VulkanContext_VulkanContext_initializeInstance
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     com_kgaft_ResonanceEngine_Native_VulkanContext_VulkanContext
 * Method:    enumerateSupportedDevices
 * Signature: (Lcom/kgaft/ResonanceEngine/Native/VulkanContext/DeviceBuilder;Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_com_kgaft_ResonanceEngine_Native_VulkanContext_VulkanContext_enumerateSupportedDevices
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
