/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kgaft_ResonanceEngine_Native_VulkanContext */

#ifndef _Included_com_kgaft_ResonanceEngine_Native_VulkanContext
#define _Included_com_kgaft_ResonanceEngine_Native_VulkanContext
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kgaft_ResonanceEngine_Native_VulkanContext
 * Method:    initializeInstance
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_kgaft_ResonanceEngine_Native_VulkanContext_initializeInstance
  (JNIEnv *, jclass, jstring, jlong);

#ifdef __cplusplus
}
#endif
#endif
