/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kgaft_ResonanceEngine_Native_VulkanContext_PhysicalDevice */

#ifndef _Included_com_kgaft_ResonanceEngine_Native_VulkanContext_PhysicalDevice
#define _Included_com_kgaft_ResonanceEngine_Native_VulkanContext_PhysicalDevice
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kgaft_ResonanceEngine_Native_VulkanContext_PhysicalDevice
 * Method:    getDeviceName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_kgaft_ResonanceEngine_Native_VulkanContext_PhysicalDevice_getDeviceName
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
