/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kgaft_ResonanceEngine_Native_Window */

#ifndef _Included_com_kgaft_ResonanceEngine_Native_Window
#define _Included_com_kgaft_ResonanceEngine_Native_Window
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kgaft_ResonanceEngine_Native_Window
 * Method:    createWindow
 * Signature: (IILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_kgaft_ResonanceEngine_Native_Window_createWindow
  (JNIEnv *, jclass, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
