/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kgaft_ResonanceEngine_Native_NativeMain */

#ifndef _Included_com_kgaft_ResonanceEngine_Native_NativeMain
#define _Included_com_kgaft_ResonanceEngine_Native_NativeMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kgaft_ResonanceEngine_Native_NativeMain
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kgaft_ResonanceEngine_Native_NativeMain_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
